name: Deploy JEPPER

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}
      - name: Deploy
        run: /bin/bash deploy.sh ${{ secrets.GH_PAT }}
